Use HTTPS for talking to PyPI
because PyPI requires it now; otherwise you get:

```
  File "/opt/prism/local/lib/python2.7/site-packages/pyramid/config/views.py", line 348, in rendered_view
    result = view(context, request)
  File "/opt/prism/src/cheeseprism/cheeseprism/views.py", line 93, in find_package
    releases = PyPi.search(search_term)
  File "/opt/prism/src/cheeseprism/cheeseprism/rpc.py", line 34, in search
    return client.package_releases(package_name, show_hidden)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1233, in __call__
    return self.__send(self.__name, args)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1587, in __request
    verbose=self.__verbose
  File "/usr/lib/python2.7/xmlrpclib.py", line 1273, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/usr/lib/python2.7/xmlrpclib.py", line 1321, in single_request
    response.msg,
ProtocolError: <ProtocolError for pypi.python.org/pypi: 403 Must access using HTTPS instead of HTTP>
```